---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/data
  verbs:
  - update
- apiGroups:
  - terraform.hammadzf.github.io
  resources:
  - staterescues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.hammadzf.github.io
  resources:
  - staterescues/finalizers
  verbs:
  - update
- apiGroups:
  - terraform.hammadzf.github.io
  resources:
  - staterescues/status
  verbs:
  - get
  - patch
  - update
