apiVersion: terraform.hammadzf.github.io/v1
kind: StateRescue
metadata:
  labels:
    app.kubernetes.io/name: tf-state-rescuer
    app.kubernetes.io/managed-by: kustomize
  name: staterescue-sample
spec:
  stateSecretName: "tfstate-default-state"
